# Use the official Python image as the base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script and CSV file into the container

# Install the required Python packages
RUN pip install pandas confluent-kafka
