/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.Uber;
import model.UberHistory;

/**
 *
 * @author pranav
 */

public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    UberHistory history ;
    public CreateJPanel(UberHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblmanufact = new javax.swing.JLabel();
        txtmanufact = new javax.swing.JTextField();
        lblmodel = new javax.swing.JLabel();
        lblserial = new javax.swing.JLabel();
        lblseat = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblyear = new javax.swing.JLabel();
        lblmaintenance = new javax.swing.JLabel();
        txtmodel = new javax.swing.JTextField();
        txtserial = new javax.swing.JTextField();
        txtseat = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        btnSaveAction = new javax.swing.JButton();
        lblavailability = new javax.swing.JLabel();
        txtavailable = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblvalid2 = new javax.swing.JLabel();
        lblvalid4 = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create");

        lblmanufact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmanufact.setText("1.Manufacturer :");

        txtmanufact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmanufactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmanufactKeyReleased(evt);
            }
        });

        lblmodel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmodel.setText("2.Model :");

        lblserial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblserial.setText("3.Serial Number:");

        lblseat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblseat.setText("4.Seats:");

        lblcity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcity.setText("5.City:");

        lblyear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblyear.setText("6. Manufactured Year:");

        lblmaintenance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmaintenance.setText("7.maintenance certificate date:");

        txtserial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtserialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtserialKeyReleased(evt);
            }
        });

        txtseat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtseatKeyPressed(evt);
            }
        });

        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcityKeyPressed(evt);
            }
        });

        txtyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtyearKeyPressed(evt);
            }
        });

        btnSaveAction.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSaveAction.setText("Save");
        btnSaveAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionActionPerformed(evt);
            }
        });

        lblavailability.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblavailability.setText("8.availabel");

        jLabel1.setText("YES/NO");

        lblvalid2.setForeground(new java.awt.Color(255, 51, 51));

        lblvalid4.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnSaveAction)))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblserial, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmaintenance)
                    .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblseat, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblavailability))
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtyear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(txtcity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtseat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtserial, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmodel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmanufact, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvalid4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblvalid2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblTitle, lblcity, lblmaintenance, lblmanufact, lblmodel, lblseat, lblserial, lblyear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblserial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvalid2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblseat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblvalid4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblavailability, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveAction)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblTitle, lblcity, lblmaintenance, lblmanufact, lblmodel, lblseat, lblserial, lblyear});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionActionPerformed
        // TODO add your handling code here:
        if(txtmanufact.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "the name field is empty");
        else if(txtmodel.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "the model field is empty");
        else if(txtserial.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "the serial field is empty");
        else if(txtseat.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "the seat field is empty");
        else if(txtcity.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "the city field is empty");
        else if(txtyear.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "the year field is empty");
       
        else if(txtavailable.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "the avaiblity field is empty");
        
        else{
        
        
        String Manufacturer = txtmanufact.getText();
        String Model = txtmodel.getText();
        long Serial = Long.valueOf(txtserial.getText()); 
        int Seat = Integer.parseInt(txtseat.getText());
        String City = txtcity.getText();
        int year = Integer.parseInt(txtyear.getText());
        //String Maintenance = txtmainten.getText();
        String Available = txtavailable.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date= sdf.format(jDateChooser1.getDate());
        Uber ub = history.addNewData();
                
        ub.setManufacturer(Manufacturer);
        ub.setModel(Model);
        ub.setSerial(Serial);
        ub.setSeat(Seat);
        ub.setCity(City);
        ub.setYear(year);
        ub.setdate(date);
        ub.setAvailabel(Available);
       
        JOptionPane.showMessageDialog(this, "new data added");
        
        txtmanufact.setText("");
        txtmodel.setText("");
        txtserial.setText("");
        txtseat.setText("");
        txtcity.setText("");
        txtyear.setText("");
        jDateChooser1.setDateFormatString("");
        txtavailable.setText("");
        }
    }//GEN-LAST:event_btnSaveActionActionPerformed

    private void txtmanufactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmanufactKeyReleased
 
    }//GEN-LAST:event_txtmanufactKeyReleased

    private void txtmanufactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmanufactKeyPressed
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(Character.isLetter(a)||Character.isWhitespace(a)||Character.isISOControl(a)){   
            txtmanufact.setEditable(true);
        }else{
         txtmanufact.setEditable(false);
            }
             
    }//GEN-LAST:event_txtmanufactKeyPressed

    private void txtserialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserialKeyReleased
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_txtserialKeyReleased

    private void txtserialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserialKeyPressed
        // TODO add your handling code here:
         char b = evt.getKeyChar();
        if(Character.isLetter(b)){
        txtserial.setEditable(false);
        }else{
        txtserial.setEditable(true);
        }
        String BAN = txtserial.getText();
        if((BAN.length()>3)&&(BAN.length()<5)){
        lblvalid2.setText(null);
        
        }else{
        lblvalid2.setText("incorrect");
        
        
        }
    }//GEN-LAST:event_txtserialKeyPressed

    private void txtseatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtseatKeyPressed

         char b = evt.getKeyChar();
        if(Character.isLetter(b)){
        txtseat.setEditable(false);
        }else{
        txtseat.setEditable(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseatKeyPressed

    private void txtyearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtyearKeyPressed
        // TODO add your handling code here:
         char b = evt.getKeyChar();
        if(Character.isLetter(b)){
        txtyear.setEditable(false);
        }else{
        txtyear.setEditable(true);
        }
        String BAN = txtyear.getText();
        if((BAN.length()>2)&&(BAN.length()<4)){
        lblvalid4.setText(null);
        
        }else{
        lblvalid4.setText("incorrect");
        
        
        }
        
    }//GEN-LAST:event_txtyearKeyPressed

    private void txtcityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyPressed
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(Character.isLetter(a)||Character.isWhitespace(a)||Character.isISOControl(a)){   
            txtcity.setEditable(true);
        }else{
         txtcity.setEditable(false);
            }
             
    }//GEN-LAST:event_txtcityKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveAction;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblavailability;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblmaintenance;
    private javax.swing.JLabel lblmanufact;
    private javax.swing.JLabel lblmodel;
    private javax.swing.JLabel lblseat;
    private javax.swing.JLabel lblserial;
    private javax.swing.JLabel lblvalid2;
    private javax.swing.JLabel lblvalid4;
    private javax.swing.JLabel lblyear;
    private javax.swing.JTextField txtavailable;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtmanufact;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtseat;
    private javax.swing.JTextField txtserial;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
