/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import com.sun.jdi.connect.spi.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Database;
import model.Uber;
import model.UberHistory;

/**
 *
 * @author pranav
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    DefaultTableModel model;
    Database uberData;
    UberHistory history;
    public ViewJPanel(UberHistory history) {
        initComponents();
        this.history = history  ; 
         
//        System.out.println(cl);
        populateTable();
        setRecords();
        
    }
    public void setRecords(){
        
        uberData = new Database();
        Object[][] ubrData = uberData.getDatabseData();
        
        //System.out.print(ubrData);
//        for (Uber db: uber)
         for(int i=0; i<uberData.getDatabseData().length; i++){
//       
        Uber uberD = history.addNewData();
        uberD.setManufacturer(ubrData[i][0].toString());
        uberD.setModel(ubrData[i][1].toString());
        uberD.setSerial(Long.parseLong(ubrData[i][2].toString()));
        uberD.setSeat(Integer.parseInt(ubrData[i][3].toString()));
        uberD.setYear(Integer.parseInt(ubrData[i][4].toString()));
        uberD.setCity(ubrData[i][5].toString());
        uberD.setdate(ubrData[i][6].toString());
        uberD.setAvailabel(ubrData[i][7].toString());
        populateTable();
         }
            // System.out.println(uberData[i][0].toString());
                
//            System.out.println(obj);
//            model1 = (DefaultTableModel)tblUberdata.getModel();
//            model1.addRow(obj);
//        }
    
    } 
    public void search(String str){
    model = (DefaultTableModel) tblUberdata.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    tblUberdata.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUberdata = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblmodel = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblserial = new javax.swing.JLabel();
        txtyear = new javax.swing.JTextField();
        txtmaintenance = new javax.swing.JTextField();
        lblseat = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblyear = new javax.swing.JLabel();
        lblmaintenance = new javax.swing.JLabel();
        lblmanufact = new javax.swing.JLabel();
        txtmodel = new javax.swing.JTextField();
        txtserial = new javax.swing.JTextField();
        txtmanufact = new javax.swing.JTextField();
        txtseat = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnvsave = new javax.swing.JButton();
        txtavailable = new javax.swing.JTextField();
        lblavailable = new javax.swing.JLabel();
        lblsearch = new javax.swing.JLabel();
        btnfind1 = new javax.swing.JButton();
        txtsearch1 = new javax.swing.JTextField();
        lblfirst = new javax.swing.JLabel();
        lbltwo = new javax.swing.JLabel();
        lblthree = new javax.swing.JLabel();
        lblfour = new javax.swing.JLabel();
        btnfind2 = new javax.swing.JButton();
        txtsearch2 = new javax.swing.JTextField();
        txtsearch3 = new javax.swing.JTextField();
        lblfive = new javax.swing.JLabel();
        lblsix = new javax.swing.JLabel();
        lblseven = new javax.swing.JLabel();
        lblten = new javax.swing.JLabel();
        lbleight = new javax.swing.JLabel();
        lblnine = new javax.swing.JLabel();
        lbleleven = new javax.swing.JLabel();
        btnfind3 = new javax.swing.JButton();
        txtsearch4 = new javax.swing.JTextField();
        txtsearch5 = new javax.swing.JTextField();
        txtsearch6 = new javax.swing.JTextField();
        txtsearch7 = new javax.swing.JTextField();
        btnfind5 = new javax.swing.JButton();
        spinnermin = new javax.swing.JSpinner();
        spinnermax = new javax.swing.JSpinner();
        btnfind6 = new javax.swing.JButton();
        txtfleet = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View");

        tblUberdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Manufacturer", "Model ", "Serial Number", "Number of Seats", "City", "Manufactured year", "Maintenance Cerificate Date", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUberdata);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblmodel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmodel.setText("2.Model  :");

        lblserial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblserial.setText("3.Serial Number:");

        lblseat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblseat.setText("4.Seats:");

        lblcity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcity.setText("5.City:");

        lblyear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblyear.setText("6. Manufactured Year:");

        lblmaintenance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmaintenance.setText("7.Maintenance certificate date:");

        lblmanufact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmanufact.setText("1.Manufacturer :");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnvsave.setText("Save");
        btnvsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvsaveActionPerformed(evt);
            }
        });

        lblavailable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblavailable.setText("8.Available");

        lblsearch.setText("Search :");

        btnfind1.setText("Find.");
        btnfind1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfind1ActionPerformed(evt);
            }
        });

        txtsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearch1ActionPerformed(evt);
            }
        });
        txtsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch1KeyReleased(evt);
            }
        });

        lblfirst.setText("1.Find me the first available passenger car:");

        lbltwo.setText("2.how many cars are available and not available");

        lblthree.setText("3.List all the car that are made by :");

        lblfour.setText("4.List the car of manufracture year of:");

        btnfind2.setText("Availabel");
        btnfind2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfind2ActionPerformed(evt);
            }
        });

        txtsearch2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch2KeyReleased(evt);
            }
        });

        txtsearch3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch3KeyReleased(evt);
            }
        });

        lblfive.setText("5.List all car with min x and max y seats:");

        lblsix.setText("6.Find car with given Serial Number:");

        lblseven.setText("7.list the car of model :");

        lblten.setText("10.list all car in given city:");

        lbleight.setText("8.list all car manufacturer:");

        lblnine.setText("9.last fleet updation date:");

        lbleleven.setText("11.list all car that expire maintenance cert.:");

        btnfind3.setText("Find.");
        btnfind3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfind3ActionPerformed(evt);
            }
        });

        txtsearch4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch4KeyReleased(evt);
            }
        });

        txtsearch5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch5KeyReleased(evt);
            }
        });

        txtsearch6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch6KeyReleased(evt);
            }
        });

        txtsearch7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch7KeyReleased(evt);
            }
        });

        btnfind5.setText("Find.");
        btnfind5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfind5ActionPerformed(evt);
            }
        });

        btnfind6.setText("Unavailabel");
        btnfind6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfind6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblten)
                            .addComponent(lbleleven)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtsearch1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblavailable)
                                            .addComponent(lblmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblserial, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblmaintenance)
                                            .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblseat, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtseat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblfirst)
                                    .addComponent(lbltwo)
                                    .addComponent(lblthree)
                                    .addComponent(lblfour)
                                    .addComponent(lblfive)
                                    .addComponent(lblsix)
                                    .addComponent(lblseven)
                                    .addComponent(lbleight)
                                    .addComponent(lblnine)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(btnvsave)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtsearch2)
                                            .addComponent(btnfind2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtsearch3)
                                            .addComponent(btnfind3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtsearch4)
                                            .addComponent(txtsearch5)
                                            .addComponent(txtsearch6)
                                            .addComponent(txtsearch7)
                                            .addComponent(btnfind5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(spinnermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(spinnermax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnfind6)))
                                        .addGap(0, 14, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnView)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnfind1)
                                    .addComponent(txtfleet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnView)
                                .addComponent(btnUpdate)
                                .addComponent(btnDelete)
                                .addComponent(txtsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnfind1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtmanufact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblfirst)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbltwo)
                                    .addComponent(btnfind2)
                                    .addComponent(btnfind6))))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblserial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtserial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblthree)
                            .addComponent(txtsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblseat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblfour)
                                .addComponent(txtsearch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfive)
                            .addComponent(btnfind3)
                            .addComponent(spinnermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnermax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblyear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblsix)
                            .addComponent(txtsearch4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblseven)
                            .addComponent(txtsearch5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtsearch6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnvsave)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblnine)
                                    .addComponent(txtfleet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblten)
                                    .addComponent(txtsearch7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbleleven)
                                    .addComponent(btnfind5))
                                .addContainerGap())))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbleight))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblUberdata.getSelectedRow();
        
        if (selectedRowIndex<0){
        JOptionPane.showMessageDialog(this,"please select the row");
        return; 
        }
        DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        Uber selectedUber = (Uber)model.getValueAt(selectedRowIndex, 0);
        history.deleteData(selectedUber);
        
        JOptionPane.showMessageDialog(this,"row deleted sucessfully");
       
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        btnvsave.enableInputMethods(false);
        int selectedRowIndex = tblUberdata.getSelectedRow();
        
        if (selectedRowIndex<0){
        JOptionPane.showMessageDialog(this,"please select the row");
        return; 
        }
        DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        Uber selectedUber = (Uber)model.getValueAt(selectedRowIndex, 0);
        
        txtmanufact.setText(selectedUber.getManufacturer());
        txtmodel.setText(selectedUber.getModel());
        txtserial.setText(String.valueOf(selectedUber.getSerial()));
        txtseat.setText(String.valueOf(selectedUber.getSeat()));
        txtcity.setText(selectedUber.getCity());
        txtyear.setText(String.valueOf(selectedUber.getYear()));
        txtmaintenance.setText(String.valueOf(selectedUber.getdate()));
        txtavailable.setText(selectedUber.getAvailabel());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnvsave.enableInputMethods(true);
        int selectedRowIndex = tblUberdata.getSelectedRow();
        
        if (selectedRowIndex<0){
        JOptionPane.showMessageDialog(this,"please select the row");
        return; 
        }
        Date thisDate = new Date();
        SimpleDateFormat dateForm = new SimpleDateFormat("MM/dd/YYYY hh:mm a");
        txtfleet.setText(dateForm.format(thisDate));
        
        DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        Uber selectedUber = (Uber)model.getValueAt(selectedRowIndex, 0);
        
        txtmanufact.setText(selectedUber.getManufacturer());
        txtmodel.setText(selectedUber.getModel());
        txtserial.setText(String.valueOf(selectedUber.getSerial()));
        txtseat.setText(String.valueOf(selectedUber.getSeat()));
        txtcity.setText(selectedUber.getCity());
        txtyear.setText(String.valueOf(selectedUber.getYear()));
        txtmaintenance.setText(String.valueOf(selectedUber.getdate())); 
        txtavailable.setText(selectedUber.getAvailabel());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnvsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvsaveActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblUberdata.getSelectedRow();
        
        Uber selectedUber = history.getHistory().get(selectedRowIndex);
        selectedUber.setManufacturer(txtmanufact.getText());
        selectedUber.setModel(txtmodel.getText());
        selectedUber.setSerial(Long.valueOf(txtserial.getText()));
        selectedUber.setSeat(Integer.parseInt(txtseat.getText()));
        selectedUber.setYear(Integer.parseInt(txtyear.getText()));
        selectedUber.setCity(txtcity.getText());
        selectedUber.setdate(txtmaintenance.getText());
        selectedUber.setAvailabel(txtavailable.getText());
        populateTable();
       
        
        
        
    }//GEN-LAST:event_btnvsaveActionPerformed

    private void btnfind1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfind1ActionPerformed
        // TODO add your handling code here:

        //String availabel = txtsearch1.getText();
        //System.out.println(availabel);
        //UberHistory ur = new UberHistory();
       DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        model.setRowCount(0);
        
        for(Uber ub : history.getHistory()){
          
            if(ub.getAvailabel() == "yes")
            {
             
            
          
           Object[] row = new Object[8];
            row[0] = ub;
            row[1] = ub.getModel();
            row[2] = ub.getSerial();
            row[3] = ub.getSeat();
            row[4] = ub.getCity();
            row[5] = ub.getYear();
            row[6] = ub.getdate();
            row[7] = ub.getAvailabel(); 
            
            model.addRow(row);
            break;
            }

        }

    }//GEN-LAST:event_btnfind1ActionPerformed

    private void txtsearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch1KeyReleased
        String str =txtsearch1.getText();
        search(str);
    }//GEN-LAST:event_txtsearch1KeyReleased

    private void btnfind2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfind2ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        model.setRowCount(0);
        
        for(Uber ub : history.getHistory()){
          
            if(ub.getAvailabel() == "yes")
            {
            
           Object[] row = new Object[8];
            row[0] = ub;
            row[1] = ub.getModel();
            row[2] = ub.getSerial();
            row[3] = ub.getSeat();
            row[4] = ub.getCity();
            row[5] = ub.getYear();
            row[6] = ub.getdate();
            row[7] = ub.getAvailabel(); 
            
            model.addRow(row);
            
            }

        }

    }//GEN-LAST:event_btnfind2ActionPerformed

    private void txtsearch2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch2KeyReleased
         String str =txtsearch2.getText();
         search(str);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch2KeyReleased

    private void txtsearch3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch3KeyReleased
         String str =txtsearch3.getText();
        search(str);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch3KeyReleased

    private void btnfind3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfind3ActionPerformed
        // TODO add your handling code here:
        int minimum = (int) spinnermin.getValue();
        int maximum = (int) spinnermax.getValue();
        DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        model.setRowCount(0);
        for (Uber ur :history.getHistory()){
            if(ur.getSeat()>= minimum && ur.getSeat()<= maximum){
            Object [] row = new Object[8];
            row[0] = ur;
            row[1] = ur.getModel();
            row[2] = ur.getSerial();
            row[3] = ur.getSeat();
            row[4] = ur.getCity();
            row[5] = ur.getYear();
            row[6] = ur.getdate();
            row[7] = ur.getAvailabel(); 
            
            model.addRow(row);
            }
        }
        
    }//GEN-LAST:event_btnfind3ActionPerformed

    private void txtsearch4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch4KeyReleased
         String str =txtsearch4.getText();
        search(str);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch4KeyReleased

    private void txtsearch5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch5KeyReleased
        // TODO add your handling code here:
         String str =txtsearch5.getText();
         search(str);
    }//GEN-LAST:event_txtsearch5KeyReleased

    private void txtsearch6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch6KeyReleased
        // TODO add your handling code here:
         String str =txtsearch6.getText();
         search(str);
    }//GEN-LAST:event_txtsearch6KeyReleased

    private void txtsearch7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch7KeyReleased
        // TODO add your handling code here:
         String str =txtsearch7.getText();
         search(str);
    }//GEN-LAST:event_txtsearch7KeyReleased

    private void btnfind5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfind5ActionPerformed
         DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        model.setRowCount(0);
        Date thisDate = new Date();
        SimpleDateFormat dateForm = new SimpleDateFormat("yyyy-MM-dd");
       
        for(Uber ub : history.getHistory()){
          Date newDate = null;
          try{
            newDate = new SimpleDateFormat("yyyy-MM-dd").parse(ub.getdate());
          } catch (ParseException ex) {
              newDate = new Date();
          }
           if(newDate.before(thisDate))
           {
            
           Object[] row = new Object[8];
            row[0] = ub;
            row[1] = ub.getModel();
            row[2] = ub.getSerial();
            row[3] = ub.getSeat();
            row[4] = ub.getCity();
            row[5] = ub.getYear();
            row[6] = ub.getdate();
            row[7] = ub.getAvailabel(); 
            
            model.addRow(row);
            
            }
               
        }
        
    }//GEN-LAST:event_btnfind5ActionPerformed

    private void txtsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch1ActionPerformed

    private void btnfind6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfind6ActionPerformed
        // TODO add your handling code here:
           DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        model.setRowCount(0);
        
        for(Uber ub : history.getHistory()){
          
            if(ub.getAvailabel() == "no")
            {
            
           Object[] row = new Object[8];
            row[0] = ub;
            row[1] = ub.getModel();
            row[2] = ub.getSerial();
            row[3] = ub.getSeat();
            row[4] = ub.getCity();
            row[5] = ub.getYear();
            row[6] = ub.getdate();
            row[7] = ub.getAvailabel(); 
            
            model.addRow(row);
            
            }

        }
    }//GEN-LAST:event_btnfind6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnfind1;
    private javax.swing.JButton btnfind2;
    private javax.swing.JButton btnfind3;
    private javax.swing.JButton btnfind5;
    private javax.swing.JButton btnfind6;
    private javax.swing.JButton btnvsave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblavailable;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lbleight;
    private javax.swing.JLabel lbleleven;
    private javax.swing.JLabel lblfirst;
    private javax.swing.JLabel lblfive;
    private javax.swing.JLabel lblfour;
    private javax.swing.JLabel lblmaintenance;
    private javax.swing.JLabel lblmanufact;
    private javax.swing.JLabel lblmodel;
    private javax.swing.JLabel lblnine;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JLabel lblseat;
    private javax.swing.JLabel lblserial;
    private javax.swing.JLabel lblseven;
    private javax.swing.JLabel lblsix;
    private javax.swing.JLabel lblten;
    private javax.swing.JLabel lblthree;
    private javax.swing.JLabel lbltwo;
    private javax.swing.JLabel lblyear;
    private javax.swing.JSpinner spinnermax;
    private javax.swing.JSpinner spinnermin;
    private javax.swing.JTable tblUberdata;
    private javax.swing.JTextField txtavailable;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtfleet;
    private javax.swing.JTextField txtmaintenance;
    private javax.swing.JTextField txtmanufact;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtsearch1;
    private javax.swing.JTextField txtsearch2;
    private javax.swing.JTextField txtsearch3;
    private javax.swing.JTextField txtsearch4;
    private javax.swing.JTextField txtsearch5;
    private javax.swing.JTextField txtsearch6;
    private javax.swing.JTextField txtsearch7;
    private javax.swing.JTextField txtseat;
    private javax.swing.JTextField txtserial;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
//        System.out.print("data is0" + cl.getDatabseData());
        
        DefaultTableModel model = (DefaultTableModel) tblUberdata.getModel();
        model.setRowCount(0);
        
        for(Uber ub : history.getHistory()){
        
            Object[] row = new Object[8];
            row[0] = ub;
            row[1] = ub.getModel();
            row[2] = ub.getSerial();
            row[3] = ub.getSeat();
            row[4] = ub.getCity();
            row[5] = ub.getYear();
            row[6] = ub.getdate();
            row[7] = ub.getAvailabel();
        
            model.addRow(row);
        }
    }

}
